labels:
  app-group: estafette-ci
  team: estafette-team
  language: docker

version:
  semver:
    major: 0
    minor: 0

stages:
  bake:
    image: extensions/docker:stable
    action: build
    inline: |
      FROM estafette/estafette-ci-builder:dev

      RUN dockerd --host=unix:///var/run/docker.sock --host=tcp://0.0.0.0:2375 --storage-driver=overlay2 --max-concurrent-downloads=10 &
      RUN while [ ! -f /var/run/docker.sock ] do; sleep 2; done

      RUN docker pull extensions/git-clone:dev
    repositories:
    - estafette

  push-to-docker-hub:
    image: extensions/docker:stable
    action: push
    repositories:
    - estafette
    pushVersionTag: false
    tags:
    - dev